import Head from 'next/head';
import Roadmap from '../../components/Roadmap';
import Footer from './../../components/Footer/Footer';
import Header from './../../components/Header/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="css/position.css" />
        <title>Roadmap</title>
      </Head>

      <Header />

      <Roadmap />

      <Footer />
    </div>
  );
};