export 
const transalate = {
  en: {
    pageTitle: "FAQ",
    pageSubtitle: "How can we help?",
    title: "How creatorPRO works",
    subtitle: "How does our ecosystem become trustworthy? Check out the pillars below: ",
    more: "Learn More",
    text1: "1) When a creator or his representative wants to include a project in our platform, our team checks some basic guarantees that the artist must follow in order to be able to approve their project. Amongst them:",
    text1_1: "1.1)In the case of creators and YouTube channels: the creator must belong to one of the creatorPRO's partner networks until the agreement is completely fulfilled.",
    text1_2: "1.2) In the case of artists and music professionals : the creator must be affiliated with one of creatorPRO 's partner music associations and perform the work through one of creatorPRO's partner digital distributors, record labels and publishers.",
    text2: "2) Our team evaluates all guarantees and confirms the revenue sharing link with partners, and only then approves the project in our NFTS block.",
    text3: "3) Our team also do a diligence to check the profile of the ownership, judicial questions, debts or other any question that could impact the revenue share.",
    text4: "4) After check this we were able to guarantee the receipt of part of the revenue generated with the approved projects, on the main stream platforms such as Youtube, Spotify, Deezer, Apple and more than 70 stream platforms and musical associations worldwide, guaranteeing the realization of revenue with content and also for valuing tokens.",
    titulotext2: "What exactly are NFTs?",
    texta: "NFT is a digital asset existing on a blockchain with a unique signature. The blockchain allows anyone to verify the authenticity and ownership of an NFT.",
    textb: "NFTs do not mean only digital art. NFTs can exist in different forms like images, videos, music, and text. Even tweets can be bought and sold as NFTs.",
    textc: "NFTs can also be digital clothing or plots of land in virtual world environments. NFTs can also refer to the exclusive use of a cryptocurrency wallet name.",
    textd: "NFTs are in trade since around 2017. The NFT market surged in popularity in early 2021. In August 2021, there was another rise in the trade of NFTs.",
    texte: "For some people, NFTs are a prized possession in a virtual environment that can determine their social status and personal taste in front of all.",
    textf: "For investors, NFTs are tempting because of rising prices, which can bring them good returns on trading and earn them some profit. Many buyers sell NFTs only within a few days or even hours of purchase in order to gain profit.",
    textg: "The market has recently seen a surge in price gains in cryptocurrencies like Bitcoin. This has created a group of investors who are rich in cryptocurrency and spend it on buying NFTs.",
    texth: "NFTs can help artists solve the problems related to the monetisation of artwork. NFTs can provide them with a better income as they will receive a royalty every time the NFT is sold after the initial sale.",
    texti: "NFTs don't guarantee all-time constant profits. Like cryptocurrency, NFTs are also unregulated and no one can assure their value. If the hype dies, losses could pile up instead of providing any gains.",
  },
  pt: {
    pageSubtitle: "Como podemos ajudar?",
    title: "Como creatorPRO funciona",
    subtitle: "Como nosso ecossistema se torna confiável? Confira os pilares abaixo: ",
    more: "Saiba Mais",
    text1: "1) Quando um criador ou seu representante deseja incluir um projeto em nossa plataforma, nossa equipe verifica algumas garantias básicas que o artista deve seguir para poder aprovar seu projeto. Dentre elas:",
    text1_1: "1.1) No caso de criadores e canais do YouTube: o criador deve pertencer a uma das redes parceiras do criadorPRO até que o acordo seja totalmente cumprido.",
    text1_2: "1.2) No caso de artistas e profissionais da música: o criador deve ser afiliado a uma das associações de música parceiras do criadorPRO e realizar o trabalho através de um dos distribuidores digitais, gravadoras e editores parceiros do criadorPRO.",
    text2: "2) Nossa equipe avalia todas as garantias e confirma o link de compartilhamento de receita com os parceiros, e só então aprova o projeto em nosso bloco NFTS.",
    text3: "3) Nossa equipe também faz uma diligência para verificar o perfil da propriedade, questões judiciais, dívidas ou qualquer outra questão que possa impactar na divisão da receita.",
    text4: "4) Após verificação conseguimos garantir o recebimento de parte da receita gerada com os projetos aprovados, nas principais plataformas de stream como Youtube, Spotify, Deezer, Apple e mais de 70 plataformas de stream e associações musicais em todo o mundo, garantindo a realização de receita com conteúdo e também para valorização de tokens.",
    titulotext2: "O que exatamente são NFTs?",
    texta: "NFT é um ativo digital existente em uma blockchain com uma assinatura única. O blockchain permite que qualquer pessoa verifique a autenticidade e a propriedade de um NFT.",
    textb: "NFTs não significam apenas arte digital. NFTs podem existir em diferentes formas, como imagens, vídeos, música e texto. Até os tweets podem ser comprados e vendidos como NFTs.",
    textc: "NFTs também podem ser roupas digitais ou terrenos em ambientes de mundo virtual. NFTs também podem se referir ao uso exclusivo de um nome de carteira de criptomoeda",
    textd: "As NFTs estão em negociação desde cerca de 2017. O mercado de NFT aumentou em popularidade no início de 2021. Em agosto de 2021, houve outro aumento no comércio de NFTs.",
    texte: "Para algumas pessoas, os NFTs são um bem precioso em um ambiente virtual que pode determinar seu status social e gosto pessoal diante de todos.",
    textf: "Para os investidores, as NFTs são tentadoras devido ao aumento dos preços, o que pode trazer bons retornos nas negociações e gerar algum lucro. Muitos compradores vendem NFTs apenas alguns dias ou mesmo horas após a compra para obter lucro.",
    textg: "O mercado viu recentemente um aumento nos ganhos de preço em criptomoedas como o Bitcoin. Isso criou um grupo de investidores que são ricos em criptomoedas e gastam na compra de NFTs.",
    texth: "Os NFTs podem ajudar os artistas a resolver os problemas relacionados à monetização de obras de arte. As NFTs podem fornecer a eles uma renda melhor, pois receberão royalties toda vez que a NFT for vendida após a venda inicial.",
    texti: "NFTs não garantem lucros constantes de todos os tempos. Assim como as criptomoedas, as NFTs também não são regulamentadas e ninguém pode garantir seu valor. Se o hype morrer, as perdas podem se acumular em vez de fornecer ganhos.",
  },
}